namespace NopStation.Plugin.Misc.B2B.SapIntegration.Models;
public class ErpOrderSyncSapResponseModel
{
    public string Company { get; set; }
    public decimal Quantity { get; set; }
    public string OrderUom { get; set; }
    public decimal UnitPriceExclTax { get; set; }
    public string PriceUom { get; set; }
    public decimal UnitPriceIncl { get; set; }
    public decimal DiscountIncl { get; set; }
    public decimal DiscountExcl { get; set; }
    public decimal LineTotalExcl { get; set; }
    public decimal LineTotalIncl { get; set; }
    public string Description { get; set; }
    public string StockCode { get; set; }
    public string ERPOrderLineStatus { get; set; }
    public DateTime DateRequired { get; set; }
    public DateTime DateExpected { get; set; }
    public string WarehouseCode { get; set; }
    public string DeliveryMethod { get; set; }
    public DateTime DeliveryDate { get; set; }
    public string SpecInstruct { get; set; }
    public string Customer { get; set; }
    public string OrderNumber { get; set; }
    public string CustomerReference { get; set; }
    public string EcomOrderNumber { get; set; }
    public string B2BOrderType { get; set; }
    public DateTime OrderDate { get; set; }
    public DateTime? QuoteExpiryDate { get; set; }
    public decimal TotalExcl { get; set; }
    public decimal VAT { get; set; }
    public decimal TotalIncl { get; set; }
    public decimal ShippingFees { get; set; }
    public string ERPOrderStatus { get; set; }
    public string SpecialInstructions { get; set; }
    public string ShippingName { get; set; }
    public string ShippingPhone { get; set; }
    public string ShippingEmail { get; set; }
    public string ShippingAddress1 { get; set; }
    public string ShippingAddress2 { get; set; }
    public string ShippingCity { get; set; }
    public string ShippingPostalCode { get; set; }
    public string ShippingCountryCode { get; set; }
    public string ShippingProvince { get; set; }
    public string BillingName { get; set; }
    public string BillingPhone { get; set; }
    public string BillingEmail { get; set; }
    public string BillingAddress1 { get; set; }
    public string BillingAddress2 { get; set; }
    public string BillingCity { get; set; }
    public string BillingPostalCode { get; set; }
    public string BillingCountryCode { get; set; }
    public string BillingProvince { get; set; }
    public string Salesperson { get; set; }
    public string Salesperson1 { get; set; }
    public string Salesperson2 { get; set; }
    public string Salesperson3 { get; set; }
}
