# List of stages for jobs, and their order of execution
stages:
  - checkout
  - build
  - publish
  - stop_website
  - deploy
  - rollback
  - start_website

variables:
  ARTIFACTS_DIR_LIVE: "C:\\Gitlab-CI-CD\\artifacts"
  PLUGINS_DIR_LIVE: "C:\\Gitlab-CI-CD\\artifacts\\Plugins"
  DEPLOY_DIR_SITE1_LIVE: "C:\\HostingSpaces\\MAC005\\macsteeltest.comalytics.com\\wwwroot\\Plugins"
  ROOT_DIR_LIVE: "C:\\Gitlab-CI-CD"
  SCRIPT_DIR_LIVE: "C:\\Gitlab-CI-CD\\scripts"
  CACHE_DIR_LIVE: "C:\\Gitlab-runner\\builds\\t3_p7s5mV\\0\\nop-station\\comalytics-nopstation-b2b-nop-470\\src\\Presentation\\Nop.Web\\Plugins"
  BACKUP_DIR_SITE1_LIVE: "C:\\Gitlab-CI-CD\\backup\\macsteel"
  LIVE_SITE1_NAME: "online.macsteeltest.comalytics.com"
  BRANCH_LIVE: "clients/macsteel/develop"

checkout_live:
  stage: checkout
  tags:
    - b2b-live-server
  script:
    - git config --system core.longpaths true
    - git config --global advice.nameTooLong false
    - git config --global safe.directory '*'
    - git checkout $BRANCH_LIVE
    - git pull
  only:
    - clients/macsteel/develop

build_live:
  stage: build
  tags:
    - b2b-live-server
  script:
    - cd $SCRIPT_DIR_LIVE
    - ls
    - powershell -File build_project.ps1
  only:
    - clients/macsteel/develop
  cache:
    key: "${CI_COMMIT_REF_NAME}-build-cache"
    paths:
      - $CACHE_DIR_LIVE

publish_live:
  stage: publish
  tags:
    - b2b-live-server
  environment: production
  script:
    - |
      try {
        if (Test-Path $ARTIFACTS_DIR_LIVE) {
          Remove-Item -Path "$ARTIFACTS_DIR_LIVE\*" -Recurse -Force
          Write-Host "Cleaned existing artifacts from $ARTIFACTS_DIR_LIVE"
        }
      } catch {
        Write-Host "Warning: Could not clean artifacts directory: $_"
      }
    - |
      try {
        if (-not (Test-Path $ARTIFACTS_DIR_LIVE)) {
          New-Item -ItemType Directory -Path $ARTIFACTS_DIR_LIVE -Force
          Write-Host "Created artifacts directory: $ARTIFACTS_DIR_LIVE"
        }
      } catch {
        Write-Host "Error: Could not create artifacts directory: $_"
        exit 1
      }
    - cd $SCRIPT_DIR_LIVE
    - ls
    - powershell -File publish_project.ps1
  only:
    - clients/macsteel/develop
  cache:
    key: "${CI_COMMIT_REF_NAME}-build-cache"
    paths:
      - $CACHE_DIR_LIVE


stop-website_live:
  stage: stop_website
  tags:
    - b2b-live-server
  script:
    - Stop-Website $LIVE_SITE1_NAME
    - Stop-WebAppPool -Name $LIVE_SITE1_NAME 
    - echo "Waiting for 2 minutes to ensure file locks are released..."
    - powershell -Command "Start-Sleep -Seconds 120"
  only:
    - clients/macsteel/develop


deploy_live:
  stage: deploy
  tags:
    - b2b-live-server
  script:
    - |
      try {
        xcopy $DEPLOY_DIR_SITE1_LIVE $BACKUP_DIR_SITE1_LIVE /y /c /h /e /r /s
      } catch {
        Write-Host "Warning: Failed to back up from $DEPLOY_DIR_SITE1_LIVE to $BACKUP_DIR_SITE1_LIVE."
      }
    - |
      try {
        xcopy $PLUGINS_DIR_LIVE $DEPLOY_DIR_SITE1_LIVE /y /c /h /e /r /s
      } catch {
        Write-Host "Warning: Failed to deploy plugins from $PLUGINS_DIR_LIVE to $DEPLOY_DIR_SITE1_LIVE."
      }
  only:
    - clients/macsteel/develop
  retry: 2   


rollback_live:
  stage: rollback
  tags:
    - b2b-live-server
  script:
    - echo "Deploy failed. Rolling back to previous version..."
    - xcopy "$BACKUP_DIR_SITE1_LIVE\\" "$DEPLOY_DIR_SITE1_LIVE" /y /c /h /e /r /s
  only:
    - clients/macsteel/develop
  when: on_failure
  needs:
    - deploy_live

start-website_live:
  stage: start_website
  tags:
    - b2b-live-server
  script:
    - Start-WebAppPool -Name $LIVE_SITE1_NAME
    - Start-Website $LIVE_SITE1_NAME
  only:
    - clients/macsteel/develop
  when: always
  
  